endNewS
amonyalife/unicodeOne pull request #3
Opened 2021-07-23 15:51 UTC by amonyalife

2021-07-23 17:49 UTC, aalystama requested changes

2021-07-23 17:49 UTC, aalystama commented on lib/main.dart
> +import 'package:flutter/material.dart';
Ты уже используешь `cupertino` нет необходимости импортировать `material`.

2021-07-23 17:49 UTC, aalystama commented on lib/src/common/widgets/text/text_Widget.dart
> +  }) : super(key: key);
Зачем тебе все эти параметры, если ты используешь только 3: `textData, maxLines, textColor`?

2021-07-23 17:49 UTC, aalystama commented on lib/src/screens/main_Screen.dart
>  import 'package:flutter/material.dart';
Смотрим первый комментарий...

2021-07-23 17:49 UTC, aalystama commented on lib/src/screens/main_Screen.dart
> +          activeColor: Colors.red,
Так как ты используешь cupertino-стиль, то используй не `Colors`, а `CupetinoColors`. `Colors `относится к material дизайну.

2021-07-23 17:49 UTC, aalystama commented on lib/src/screens/main_Screen.dart
> +              icon: Icon(Icons.account_circle_outlined),
Тут тоже... `Icons` -> `CupertinoIcons`.

2021-07-23 17:49 UTC, aalystama commented on lib/src/screens/news_Screend.dart
> +import 'package:flutter/material.dart';
Первый коммент

2021-07-23 17:49 UTC, aalystama commented on lib/src/screens/profile_Screen.dart
> +import 'package:flutter/material.dart';
Первый коммент

2021-07-23 17:49 UTC, aalystama commented on pubspec.yaml
> +    - assets/image/111.png
Тут можно просто оставить `- assets/image` тогда он будет использовать все картинки в этой папке

2021-07-24 08:32 UTC, maripbekoff commented on lib/main.dart
> +import 'package:amonyatest/src/screens/main_Screen.dart';
Название файлов должны писаться с `snake_case.dart` без заглавных букв. Но это конечно не критично, не обязательно менять. Но просто учитывай это, т.к. многие используют `snake_case`.

2021-07-24 08:32 UTC, maripbekoff commented on lib/main.dart
> +          scaffoldBackgroundColor: AppColor.scaffoldColor,
Название для scaffoldColor можно оптимизировать. 
1. Название класса имеет `Color`, поэтому ставить для поля color не обязательно. 
2. Название желательно должно точно описывать для чего используется константа. Вместо `scaffold` лучше переименовать в `scaffoldBackground`

2021-07-24 08:33 UTC, maripbekoff commented
Можешь мерджить

2021-07-25 15:54 UTC, merged